
[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "v1.4.0"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "v2.5.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "v1.1.0"
